[theme]
base = "dark"  # of laat weg als je alleen dark wilt

primaryColor = "#6ea8fe"       # zacht blauw accent, goed op dark
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#c9d1d9"
font = "sans serif"            # helvetica werkt, maar sans serif is veiliger


#base = "dark"
#primaryColor = "#0C111D"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor = "#F0F1F1"
#textColor = "#0C111D"
#font = "helvetica"
